language: node_js
node_js: stable

cache:
    directories:
        - node_modules


before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

before_script:
  - git config user.name "Babysbreath-x"
  - git config user.email "490749127@qq.com"

script:
  - hexo clean
  - hexo generate
  - hexo deploy

#after_script:
  # - cd ./public
  # - git init
  # - git add .
  # - git commit -m "TravisCI ×Ô¶¯²¿Êð"
  # Github Pages
  # - sed -i "s/gh_token/${token_name}/g" ./_config.yml
  # - git push --force --quiet "https://GH_TOKEN@${GH_REF}" master:master

#env:
  #global:
    # - GH_REF: github.com/Babysbreath-x/Babysbreath-x.github.io.git

branches:
  only:
    - master
  
notifications:
  email:
    - 490749127@qq.com
  on_success: change
  on_failure: always